stages:
  - development
  - deploy

variables:
  TAG_LATEST: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

deploy:
  image: alpine:latest
  stage: deploy
  tags:
    - deployment
  script:
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "source .zshrc && cd Optis/backend-managment-system && git pull origin main && git checkout $CI_COMMIT_SHORT_SHA && composer update && php artisan migrate && pm2 restart php"
  environment:
    name: production
    url: https://optis.optima.az
  only:
    - main

